"""
Session logger for Prudentia Observatory.

Writes a human-readable .log file and a machine-readable JSON log per session.
Generated by Prudentia Observatory.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import asdict
from datetime import datetime, timezone
from typing import Optional

from .models import SessionMetadata, SolveResult

log = logging.getLogger(__name__)


class SessionLogger:
    """Writes a persistent log file for the current observing session."""

    def __init__(self, log_dir: Optional[str] = None) -> None:
        if log_dir is None:
            log_dir = os.path.join(os.path.expanduser("~"), "PrudentiaObservatory", "logs")
        os.makedirs(log_dir, exist_ok=True)
        ts = datetime.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        base = os.path.join(log_dir, f"session_{ts}")
        self._log_path = f"{base}.log"
        self._json_path = f"{base}_events.json"
        self._events: list[dict] = []
        self._write_header()

    @property
    def log_path(self) -> str:
        return self._log_path

    # ─────────────────────────────────────────────────────────────────────────
    # Public logging methods
    # ─────────────────────────────────────────────────────────────────────────

    def info(self, message: str) -> None:
        self._append("INFO", message)

    def warning(self, message: str) -> None:
        self._append("WARNING", message)

    def error(self, message: str) -> None:
        self._append("ERROR", message)

    def log_capture(self, meta: SessionMetadata, image_path: str) -> None:
        self._append(
            "CAPTURE",
            f"Frame saved: {image_path} | Target: {meta.target_name} | "
            f"Exp: {meta.exposure_seconds}s | ISO: {meta.iso} | "
            f"Alt: {meta.altitude_degrees:.1f}° | Airmass: {meta.airmass:.2f}",
            extra={"metadata": asdict(meta), "image_path": image_path},
        )

    def log_solve(self, result: SolveResult) -> None:
        status = "SOLVED" if result.success else "SOLVE_FAILED"
        msg = (
            f"Plate solve: RA={result.ra_hours:.4f}h Dec={result.dec_degrees:.3f}° "
            f"Error={result.total_error_arcmin:.1f}' in {result.solver_time_seconds:.1f}s"
            if result.success
            else f"Plate solve failed: {result.message}"
        )
        self._append(status, msg, extra={"solve_result": asdict(result)})

    def log_slew(self, target_name: str, ra_hours: float, dec_degrees: float) -> None:
        self._append(
            "SLEW",
            f"Slewing to {target_name} "
            f"(RA {ra_hours:.4f}h, Dec {dec_degrees:+.3f}°)",
        )

    def log_sequence_start(
        self, target: str, frames: int, exposure: float, iso: int
    ) -> None:
        self._append(
            "SEQ_START",
            f"Sequence started: {target} | {frames} × {exposure}s @ ISO {iso}",
        )

    def log_sequence_end(self, target: str, frames_done: int, aborted: bool) -> None:
        status = "SEQ_ABORTED" if aborted else "SEQ_COMPLETE"
        self._append(status, f"Sequence ended: {target} | {frames_done} frames captured")

    def close(self) -> None:
        self._append("SESSION_END", "Prudentia Observatory session ended.")
        self._flush_json()

    # ─────────────────────────────────────────────────────────────────────────
    # Internal helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _write_header(self) -> None:
        now = datetime.now(tz=timezone.utc).isoformat()
        header = (
            "=" * 72 + "\n"
            "  Generated by Prudentia Observatory\n"
            f"  Session started: {now}\n"
            "=" * 72 + "\n"
        )
        try:
            with open(self._log_path, "w", encoding="utf-8") as f:
                f.write(header)
        except OSError:
            log.exception("Failed to create session log at %s", self._log_path)

    def _append(self, level: str, message: str, extra: Optional[dict] = None) -> None:
        now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        line = f"[{now}] [{level:12s}] {message}\n"
        try:
            with open(self._log_path, "a", encoding="utf-8") as f:
                f.write(line)
        except OSError:
            log.warning("Could not write to session log: %s", message)
        event: dict = {"timestamp": now, "level": level, "message": message}
        if extra:
            event["extra"] = extra
        self._events.append(event)

    def _flush_json(self) -> None:
        try:
            with open(self._json_path, "w", encoding="utf-8") as f:
                json.dump(self._events, f, indent=2, default=str)
        except OSError:
            log.warning("Could not write JSON session log.")
